language: python
sudo: false
python:
  - "3.5"
virtualenv:
  system_site_packages: false
install:
  # all installing is now handled by conda as it is faster and more robust
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

  - conda env create
  - source activate gala

  # custom package not available from conda
  - pip install viridis

  # install testing and coverage packages
  - pip install pytest pytest-cov
  - pip install coveralls

  # Install gala
  - printenv PWD
  # Build locally, pytest confuses local and global installs
  - python setup.py develop

script:
  # Run tests
  - py.test

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then coveralls; fi

cache:
    directories:
        - $HOME/miniconda
        - $HOME/.matplotlib
