name: gala
dependencies:
- python=3.5*
- setuptools=19.6*
- cython=0.23*
- pytest=2.8*
- numpy=1.10*
- nose=1.3*
- numpydoc=0.5*
- h5py=2.5*
- matplotlib=1.5*
- pandas=0.17*
- scipy=0.17*
- scikit-learn=0.17*
- scikit-image=0.12*
- networkx=1.10*
- jupyter=1.0*
- pyzmq=15.*
- pip:
  - coverage>=4.0
  - pytest-cov>=2.2
  - viridis>=0.4
  - memory_profiler>=0.41
  - line_profiler>=1.0
